// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "plugins/jquery/jquery.min.js"
import "plugins/jquery-ui/jquery-ui.min.js"
import "plugins/bootstrap/js/bootstrap.bundle.min.js"
import "plugins/chart.js/Chart.min.js"
import "plugins/sparklines/sparkline.js"
import "plugins/jqvmap/jquery.vmap.min.js"
import "plugins/jquery-knob/jquery.knob.min.js"
import "plugins/daterangepicker/daterangepicker.js"
import "plugins/summernote/summernote-bs4.min.js"
import "dist/js/adminlte.js"
import "dist/js/demo.js"
import "dist/js/pages/dashboard.js"
import "/dist/js/adminlte.js"
import "/assets/es-module-shims.min-d89e73202ec09dede55fb74115af9c5f9f2bb965433de1c2446e1faa6dac2470.js"